#!/bin/busybox ash

BUSYBOX=$(/bin/busybox readlink -f /bin/busybox)

alias busybox="$BUSYBOX"

busybox mount -t proc proc /proc
busybox mount -t sysfs sys /sys
busybox mount -t devtmpfs dev /dev
busybox mount -t tmpfs tmpfs /tmp

/sbin/modprobe e1000
busybox ip l set eth0 up
busybox udhcpc -fqs /udhcpc.script

/sbin/modprobe btrfs
busybox mkdir -p /mnt/lower /tmp/upper /tmp/work /mnt/merged
busybox mount /dev/sdb /mnt/lower
/sbin/modprobe overlay
busybox mount -t overlay -olowerdir=/mnt/lower,upperdir=/tmp/upper,workdir=/tmp/work overlay /mnt/merged

busybox mkdir -p /mnt/merged/dev /mnt/merged/sys /mnt/merged/proc
busybox mount -o move /dev /mnt/merged/dev
busybox mount -o move /sys /mnt/merged/sys
busybox mount -o move /proc /mnt/merged/proc

MODULES_PATH="/lib/modules/$(/bin/busybox uname -r)"
busybox mkdir -p /mnt/merged/.old_root /mnt/merged"$MODULES_PATH"
# See mount(8)
busybox mount -o bind "$MODULES_PATH" /mnt/merged"$MODULES_PATH"
busybox mount -o remount,bind,ro,nodev,noexec "$MODULES_PATH" /mnt/merged"$MODULES_PATH"

busybox mkdir /mnt/merged/.c2v
busybox touch /mnt/merged/.c2v/busybox
busybox mount -o bind "$BUSYBOX" /mnt/merged/.c2v/busybox
busybox mount -o remount,bind,ro "$BUSYBOX" /mnt/merged/.c2v/busybox

busybox umount /mnt/lower
busybox umount /tmp

busybox pivot_root /mnt/merged/ /mnt/merged/.old_root

exec /.c2v/busybox ash /.c2v_init
