#!/busybox ash

set -e

alias busybox="/busybox"
alias modprobe="/modprobe"

busybox mkdir -p /proc /sys /dev /tmp /etc
busybox mount -t proc proc /proc
# now busybox standalone mode should work
mount -t sysfs sys /sys
mount -t devtmpfs dev /dev
mount -t tmpfs tmpfs /tmp

find /sys/devices -name modalias -type f -print0 | xargs -0 /busybox sort -u | xargs /modprobe -ab 2>/dev/null || true

modprobe squashfs || true
MODULES_PATH="/lib/modules/$(busybox uname -r)"
mkdir -p /mnt/modules"$MODULES_PATH"
mount -t squashfs /dev/sda /mnt/modules"$MODULES_PATH"

find /sys/devices -name modalias -type f -print0 | xargs -0 /busybox sort -u | xargs /modprobe -d /mnt/modules -ab 2>/dev/null || true

alias modprobe="/modprobe -d /mnt/modules"

set -- $(cat /proc/cmdline)
for i; do
	case "$i" in
	hostname=*)
		HOSTNAME="${i#hostname=}"
		;;
	ifaddr=*)
		IFADDR="${i#ifaddr=}"
		;;
	gwaddr=*)
		GWADDR="${i#gwaddr=}"
		;;
	nameserver=*)
		NAMESERVER="${i#nameserver=}"
		;;
	esac
done

HOSTNAME=${HOSTNAME:-$(head -c 6 /dev/urandom | hexdump -e '6/1 "%02x"')}
echo "$HOSTNAME" > /etc/hostname
hostname "$HOSTNAME"

modprobe btrfs || true
mkdir -p /mnt/lower /tmp/upper /tmp/work /mnt/merged
mount /dev/sdb /mnt/lower
modprobe overlay || true
mount -t overlay -olowerdir=/mnt/lower,upperdir=/tmp/upper,workdir=/tmp/work overlay /mnt/merged

ip l set eth0 up
if [ -n "$IFADDR" ]; then
	ip a add "$IFADDR" dev eth0
	[ -n "$GWADDR" ] && ip r add default via "$GWADDR" dev eth0
	if [ -n "$NAMESERVER" ]; then
		echo "nameserver $NAMESERVER" > /etc/resolv.conf
	fi
else
	modprobe af_packet || true
	udhcpc -fqs /udhcpc.script
fi

touch /mnt/merged/.c2v/busybox
# See mount(8)
mount -o bind /busybox /mnt/merged/.c2v/busybox
mount -o remount,bind,ro /busybox /mnt/merged/.c2v/busybox

touch /mnt/merged/.c2v/setuidgid
mount -o bind /setuidgid /mnt/merged/.c2v/setuidgid
mount -o remount,bind,ro /setuidgid /mnt/merged/.c2v/setuidgid

mkdir -p /mnt/merged/etc
touch /mnt/merged/etc/resolv.conf
mount -o bind /etc/resolv.conf /mnt/merged/etc/resolv.conf
mount -o remount,bind,ro /etc/resolv.conf /mnt/merged/etc/resolv.conf
touch /mnt/merged/etc/hostname
mount -o bind /etc/hostname /mnt/merged/etc/hostname
mount -o remount,bind,ro /etc/hostname /mnt/merged/etc/hostname

umount /mnt/lower
umount /tmp

mkdir -p /mnt/merged/dev /mnt/merged/sys /mnt/merged/proc /mnt/merged"$MODULES_PATH"
mount -o move /mnt/modules"$MODULES_PATH" /mnt/merged"$MODULES_PATH"
mount -o move /dev /mnt/merged/dev
mount -o move /sys /mnt/merged/sys
mount -o move /proc /mnt/merged/proc

exec /busybox switch_root /mnt/merged/ /.c2v/busybox ash /.c2v/init
